let aardvark, bat, cat, duck, elephant, frigatebird, gharial, hedgehog, impala, jackal, koala, lion, monkey, narwhal, octopus, pig, quokka, raccoon, sturgeon, turkey, umbrellabird, vulture, wolf, xerus, yak, zebra;

function preload(){
  // Load Images
  aardvarkI = loadImage('Images/Aardvark.png');
  batI = loadImage('Images/Bat.png');
  catI = loadImage('Images/Cat.png');
  duckI = loadImage('Images/Duck.png')
  elephantI = loadImage('Images/Elephant.png');
  frigatebirdI = loadImage('Images/Frigatebird.png');
  gharialI = loadImage("Images/Gharial.png");
  hedgehogI = loadImage("Images/Hedgehog.png");
  impalaI = loadImage("Images/Impala.png");
  jackalI = loadImage("Images/Jackal.png");
  koalaI = loadImage("Images/Koala.png");
  lionI = loadImage("Images/Lion.png");
  monkeyI = loadImage("Images/Monkey.png");
  narwhalI = loadImage("Images/Narwhal.png");
  octopusI = loadImage("Images/Octopus.png");
  pigI = loadImage("Images/Pig.png");
  quokkaI = loadImage("Images/Quokka.png");
  raccoonI = loadImage("Images/Raccoon.png");
  sturgeonI = loadImage("Images/Sturgeon.png");
  turkeyI = loadImage("Images/Turkey.png");
  umbrellabirdI = loadImage("Images/Umbrellabird.png");
  vultureI = loadImage("Images/Vulture.png");
  wolfI = loadImage("Images/Wolf.png");
  xerusI = loadImage("Images/Xerus.png");
  yakI = loadImage("Images/Yak.png");
  zebraI = loadImage("Images/Zebra.png");
  
  // Load Sounds
  aardvark = loadSound('Sounds/Aardvark.mp3');
  bat = loadSound("Sounds/Bat.mp3");
  cat = loadSound("Sounds/Cat.mp3");
  duck = loadSound("Sounds/Duck.mp3");
  elephant = loadSound("Sounds/Elephant.mp3");
  frigatebird = loadSound("Sounds/Frigatebird.mov");
  gharial = loadSound("Sounds/Gharial.mp3");
  hedgehog = loadSound("Sounds/Hedgehog.mp3");
  impala = loadSound("Sounds/Impala.mp3");
  jackal = loadSound("Sounds/Jackal.mp3");
  koala = loadSound("Sounds/Koala.mp3");
  lion = loadSound("Sounds/Lion.mp3");
  monkey = loadSound("Sounds/Monkey.mp3");
  narwhal = loadSound("Sounds/Narwhal.mp3");
  octopus = loadSound("Sounds/Octopus.mp3");
  pig = loadSound("Sounds/Pig.mp3");
  quokka = loadSound("Sounds/Quokka.mp3");
  raccoon = loadSound("Sounds/Raccoon.mp3");
  sturgeon = loadSound("Sounds/Sturgeon.mp3");
  turkey = loadSound("Sounds/Turkey.mp3");
  umbrellabird = loadSound("Sounds/Umbrellabird.mp3");
  vulture = loadSound("Sounds/Vulture.mp3");
  wolf = loadSound("Sounds/Wolf.mp3");
  xerus = loadSound("Sounds/Xerus.mp3");
  yak = loadSound("Sounds/Yak.mp3");
  zebra = loadSound("Sounds/Zebra.mp3");
}
